name: MinecraftGPT
version: 1.0
main: com.minecraft.gpt.MinecraftGPT
api-version: '1.20'
description: A Minecraft plugin that lets players interact with GPT-4
commands:
  ask:
    description: Ask GPT-4 a question about Minecraft
    usage: /ask <question>
    permission: minecraftgpt.ask
permissions:
  minecraftgpt.ask:
    description: Allows players to use the /ask command
    default: true 